
version: '3'

services:
  db1:
    image: redis
    sysctls:
      net.core.somaxconn: 1024 


  web:
    build: .
    command: node app.js
    volumes:
      - .:/code
    ports:
      - "3001:3001"
    depends_on:
      - db1
