
version: '3'

services:
  db:
    image: redis
    sysctls:
      net.core.somaxconn: 1024 
    ports:
      - '6379:6379'


  web:
    build: .
    command: node app.js
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
